#!/usr/bin/env python3

import getpass
import os
import sys
import hashlib


#EDIT HERE WITH YOUR LOGIN#
username = "default"
###########################

if (username == "default"):
    print("You must set your login in the script before using it")
    exit(1)

if len(sys.argv) < 2:
    print("Usage: " + sys.argv[0] + ": repository_name [login_1] [login_2] [...]")
    exit(1)
token = str(hashlib.sha512(bytes(getpass.getpass("Password: "), 'utf8')).hexdigest())
rep_name = sys.argv[1]
if (not os.system("blih -u "+username+" -t \"" + token + "\" repository create " + rep_name) and
    not os.system("blih -u "+username+" -t \"" + token + "\" repository setacl " + rep_name + " ramassage-tek r") and
    not os.system("blih -u "+username+" -t \"" + token + "\" repository setacl " + rep_name + " rush r")):

    for i in range(2, len(sys.argv)):
        print("\nAdding user: \033[94m" + sys.argv[i] + "\033[0m")
        os.system("blih -u "+username+" -t \"" + token + "\" repository setacl " + rep_name + " "  + sys.argv[i]  + " rw ")

    print("\nUsers:\033[94m")
    os.system("blih -u "+username+" -t \"" + token + "\" repository getacl " + rep_name)
    print("\033[0m")

    if (input("Do you want to clone your repository ? (Y/N)\n").upper() == "Y"):
        os.system("git clone " + username + "@git.epitech.eu:/" + username + "/" + rep_name)
